### PR TITLE
Fix 'limit' for getServerList, Allow for More or Less Responses

### LINKED ISSUE #51: getServerList Always Returns 100 Results, Incorrect Variable Name
Regardless of the number passed in for 'count', the function always returns 100 results. This is because the correct variable name in the Steam API request should actually be 'limit'. If limit is not specified, Steam will always return 100 results.

### PR DESCRIPTION
**Pull request by joshuafhiggins**
Fixes #51

### CODE REVIEW

File: src/SteamAPI.ts [hunk 1]
```diff
@@ -695,8 +695,8 @@ export default class SteamAPI {
 	 * Although a filter is not stricly required, you probably want to at least use something like \appid\[appid] to filter by app
 	 * @param count Number of results to return. 100 by default
```
Comment (xDimGG) [inline src/SteamAPI.ts:696]: Change the docstring here to limit as well

Comment (joshuafhiggins) [reply src/SteamAPI.ts]: Done!
